SELECT ROW_NUMBER() OVER (ORDER BY (Pontos)desc, (Venda) desc) Rank, CODVEND, APELIDO Vendedor, Pontos, VENDA Valor, SKU, CAST(CL as INT) Clientes, Atingido,
CASE WHEN Atingido > 70 THEN '#84f092' ELSE '#daebf5' END BKCOLOR
FROM (
SELECT CODVEND, APELIDO, VENDA, SKU, CASE WHEN CL > (TotalCL * 0.6) THEN Pontos ELSE 0 END Pontos,
TotalCL, CL, (CL/TotalCL)*100 Atingido
FROM ( 
SELECT CODVEND, APELIDO, VENDA, Pontuação1 + Pontuação2 Pontos, SKU, CL, TotalCL FROM (
SELECT CODVEND, APELIDO, VENDA, SKU10 + SKU3 Pontuação1, CL*15 Pontuação2, SKU, CAST(CL as Float) CL, CAST(TotalCL as Float) TotalCL FROM(
SELECT CODVEND, APELIDO, SUM(VENDA) VENDA, SKU10 * 10 SKU10, SKU3 * 3 SKU3, SKU, CL, TotalCL FROM (
SELECT CODVEND, APELIDO, SUM(VENDA) VENDA, SKU10,  SKU3, CL, TotalCL, (SKU10+SKU3) SKU, Pontos FROM (
SELECT DISTINCT VEN.CODVEND, VEN.APELIDO,
SUM(((ITE.VLRTOT - ITE.VLRDESC - ITE.VLRREPRED + ITE.VLRSUBST + ITE.VLRIPI) * VCAB.INDITENS ) * TPO.GOLDEV) VENDA,
CASE WHEN PRO.MARCA IN ('SUVINIL-PISO', 'SUVINIL-CORANTE LIQUIDO', 'SUVINIL-RESINA BASE D AGUA', 'SUVINIl-RESINA BASE SOLVENTE', 
'GLASU-BRILHO PRATICO', 'GLASU-CORANTES', 'GLASU-ESMALTE', 'GLASU-MASSA ACRILICA', 'GLASU-MAXIMO EFICIENCIA',
'GLASU-MUDA FACIL', 'GLASU-PINTURA ESSENCIAL', 'GLASU-SELADOR ACRILICO', 'SUVINIL-RENDE & COBRE MUITO') THEN 10 ELSE 3 END PONTOS,
SKU10.SKU SKU10, SKU3.SKU SKU3, COUNT(DISTINCT(CL)) CL, COUNT(TotalCL) TotalCL
FROM TGFCAB CAB (NOLOCK)
INNER JOIN TGFTOP TPO  (NOLOCK) ON TPO.CODTIPOPER = CAB.CODTIPOPER AND TPO.DHALTER = CAB.DHTIPOPER
INNER JOIN TGFVEN VEN  (NOLOCK) ON VEN.CODVEND    = CAB.CODVEND
RIGHT JOIN VGFCAB VCAB (NOLOCK) ON VCAB.NUNOTA    = CAB.NUNOTA
INNER JOIN TGFITE ITE  (NOLOCK) ON ITE.NUNOTA     = CAB.NUNOTA
INNER JOIN TGFPRO PRO (NOLOCK) ON ITE.CODPROD = PRO.CODPROD
INNER JOIN (
            SELECT COUNT(DISTINCT(ITE.CODPROD)) SKU, VEN.CODVEND, VEN.APELIDO
            FROM TGFCAB CAB (NOLOCK)
            INNER JOIN TGFTOP TPO  (NOLOCK) ON TPO.CODTIPOPER = CAB.CODTIPOPER AND TPO.DHALTER = CAB.DHTIPOPER
            INNER JOIN TGFVEN VEN  (NOLOCK) ON VEN.CODVEND    = CAB.CODVEND
            RIGHT JOIN VGFCAB VCAB (NOLOCK) ON VCAB.NUNOTA    = CAB.NUNOTA
            INNER JOIN TGFITE ITE  (NOLOCK) ON ITE.NUNOTA     = CAB.NUNOTA
            INNER JOIN TGFPRO PRO (NOLOCK) ON ITE.CODPROD = PRO.CODPROD
            
            WHERE
            CAB.CODVEND>0 AND
            CODPARCFORN IN (27828, 28008) AND
            VEN.ATIVO='S'
            AND CONVERT(date, CAB.DTNEG) BETWEEN '01/08/2022' AND '30/09/2022'
            AND TPO.GOLSINAL = -1
            AND CAB.STATUSNOTA = 'L'
            AND CAB.TIPMOV IN ('V') 
            AND PRO.MARCA IN ('SUVINIL-PISO', 'SUVINIL-CORANTE LIQUIDO', 'SUVINIL-RESINA BASE D AGUA', 'SUVINIl-RESINA BASE SOLVENTE', 
                'GLASU-BRILHO PRATICO', 'GLASU-CORANTES', 'GLASU-ESMALTE', 'GLASU-MASSA ACRILICA', 'GLASU-MAXIMO EFICIENCIA',
                'GLASU-MUDA FACIL', 'GLASU-PINTURA ESSENCIAL', 'GLASU-SELADOR ACRILICO', 'SUVINIL-RENDE & COBRE MUITO') 
            GROUP BY VEN.CODVEND, VEN.APELIDO
    ) SKU10 ON VEN.CODVEND = SKU10.CODVEND
    INNER JOIN (
            SELECT COUNT(DISTINCT(ITE.CODPROD)) SKU, VEN.CODVEND, VEN.APELIDO
            FROM TGFCAB CAB (NOLOCK)
            INNER JOIN TGFTOP TPO  (NOLOCK) ON TPO.CODTIPOPER = CAB.CODTIPOPER AND TPO.DHALTER = CAB.DHTIPOPER
            INNER JOIN TGFVEN VEN  (NOLOCK) ON VEN.CODVEND    = CAB.CODVEND
            RIGHT JOIN VGFCAB VCAB (NOLOCK) ON VCAB.NUNOTA    = CAB.NUNOTA
            INNER JOIN TGFITE ITE  (NOLOCK) ON ITE.NUNOTA     = CAB.NUNOTA
            INNER JOIN TGFPRO PRO (NOLOCK) ON ITE.CODPROD = PRO.CODPROD
            
            WHERE
            CAB.CODVEND>0 AND
            CODPARCFORN IN (27828, 28008) AND
            VEN.ATIVO='S'
            AND CONVERT(date, CAB.DTNEG) BETWEEN '01/08/2022' AND '30/09/2022'
            AND TPO.GOLSINAL = -1
            AND CAB.STATUSNOTA = 'L'
            AND CAB.TIPMOV IN ('V') 
            AND PRO.MARCA NOT IN ('SUVINIL-PISO', 'SUVINIL-CORANTE LIQUIDO', 'SUVINIL-RESINA BASE D AGUA', 'SUVINIl-RESINA BASE SOLVENTE', 
                'GLASU-BRILHO PRATICO', 'GLASU-CORANTES', 'GLASU-ESMALTE', 'GLASU-MASSA ACRILICA', 'GLASU-MAXIMO EFICIENCIA',
                'GLASU-MUDA FACIL', 'GLASU-PINTURA ESSENCIAL', 'GLASU-SELADOR ACRILICO', 'SUVINIL-RENDE & COBRE MUITO') 
            GROUP BY VEN.CODVEND, VEN.APELIDO
    ) SKU3 ON VEN.CODVEND = SKU3.CODVEND
    INNER JOIN (
    SELECT COUNT(DISTINCT(PAR.CODPARC)) CL, PAR.CODVEND FROM TGFPAR PAR
    INNER JOIN TGFCAB CAB ON CAB.CODPARC = PAR.CODPARC
    INNER JOIN TGFITE ITE  (NOLOCK) ON ITE.NUNOTA     = CAB.NUNOTA
    INNER JOIN TGFPRO PRO (NOLOCK) ON ITE.CODPROD = PRO.CODPROD
    INNER JOIN TGFVEN VEN ON VEN.CODVEND = PAR.CODVEND
    WHERE 
    CONVERT(date, CAB.DTNEG) BETWEEN '01/08/2022' AND '30/09/2022'
    AND PAR.ATIVO='S' 
    AND CODPARCFORN IN (27828, 28008) 
    AND CAB.STATUSNOTA = 'L'
    AND CAB.TIPMOV IN ('V') 
    GROUP BY PAR.CODVEND
    ) CL ON CL.CODVEND = VEN.CODVEND
    INNER JOIN (
    SELECT COUNT(DISTINCT(PAR.CODPARC)) TotalCL, PAR.CODVEND FROM TGFPAR PAR 
    WHERE ATIVO='S' GROUP BY CODVEND)TotalCL ON TotalCL.CODVEND = VEN.CODVEND

WHERE
CAB.CODVEND>0 AND
CODPARCFORN IN (27828, 28008) AND
VEN.ATIVO='S'
AND TPO.GOLSINAL = -1
AND CAB.STATUSNOTA = 'L'
AND CAB.TIPMOV IN ('V', 'D') 
GROUP BY VEN.CODVEND, PRO.MARCA, VEN.APELIDO, SKU10.SKU, SKU3.SKU
) Z1 GROUP BY CODVEND, APELIDO, CL, TotalCL, SKU10, SKU3, Pontos
) Z2 GROUP BY CODVEND, APELIDO, CL, TotalCL, SKU10, SKU3, SKU
)Z2 GROUP BY CODVEND, APELIDO, CL, TotalCL, SKU, VENDA, SKU10, SKU3
)Z3 GROUP BY CODVEND, APELIDO, CL, TotalCL, SKU, Pontuação1, Pontuação2, Venda
)Z4
)Z5 
ORDER BY Pontos desc, Venda desc